"use strict";
var mongoose = require('mongoose');
var config = require('../config');
var Schema = mongoose.Schema;
var _ = require('lodash');


/**
 * Each segment of a daily triplog
 */
var TriplogSegment = {
  mode:{type:String,enum:_.map(config.triplogModes,'value'),required:true},
  miles:{type:Number,required:false},
  dateTime:{type:Date,required:true}
};


/**
* TriplogSchema
*
* describes data structure for Triplog
*
* @private
* @type {Schema}
*/
var TriplogSchema = new Schema({

    // _id (generated by Mongo)
    // date, should be the equivalent of "01-01-2017 00:00:00" in the correct timezone
    date:{type:Date,required:true},

    // all trips taken that day
    segments:[TriplogSegment],

    // activity logging
    created: { type: Date, default: Date.now},
    updated: { type: Date, default: Date.now}
});

TriplogSchema.pre('save', function (next, done) {

    // set the updated time
    this.updated = Date.now();
    this.markModified('updated');
    this.markModified('segments'); // for good measure, just always update these

    // continue saving...
    next();

});

var Triplog = mongoose.model('Triplog', TriplogSchema);
module.exports = Triplog;
